version: "3.2"
services:
  setup: &setup
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    networks:
      - rss_network
    restart: on-failure

  api:
    <<: *setup
    container_name: 'api'
    ports:
      - "8000:8000"
    depends_on:
      - db

  celery:
    <<: *setup
    container_name: 'celery'
    depends_on:
      - db
      - rabbitmq
      - api
    command: "celery -A api worker -l INFO -B"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ../.env
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/
    networks:
      - rss_network
    restart: on-failure

  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - rss_network
    restart: on-failure


networks:
  rss_network:
    driver: bridge
