# Generated by Django 4.1.3 on 2022-11-13 12:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RSSItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("guid", models.CharField(max_length=300, unique=True)),
                ("title", models.CharField(max_length=300)),
                ("link", models.URLField(verbose_name="RSS item link")),
                ("author", models.CharField(default="", max_length=250, null=True)),
                ("published_date", models.DateTimeField(null=True)),
                ("last_updated", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "rss_item",
                "ordering": ("-last_updated",),
            },
        ),
        migrations.CreateModel(
            name="RSSModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("link", models.URLField(unique=True, verbose_name="RSS source link")),
                ("language", models.CharField(blank=True, default="", max_length=30)),
                ("category", models.CharField(blank=True, default="", max_length=200)),
                ("ttl", models.IntegerField(default=60, verbose_name="Refresh time range")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "rss",
            },
        ),
        migrations.CreateModel(
            name="UserRSSModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rss",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rss.rssmodel"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "user_rss",
                "index_together": {("user", "rss")},
            },
        ),
        migrations.CreateModel(
            name="UserRSSItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "following_rss",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rss.userrssmodel"
                    ),
                ),
                (
                    "rss_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rss.rssitemmodel"
                    ),
                ),
            ],
            options={
                "db_table": "user_rss_items",
                "ordering": ["-rss_item__published_date"],
                "index_together": {("following_rss", "rss_item")},
            },
        ),
        migrations.AddField(
            model_name="rssmodel",
            name="users",
            field=models.ManyToManyField(through="rss.UserRSSModel", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="rssitemmodel",
            name="rss",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rss.rssmodel"),
        ),
        migrations.AddField(
            model_name="rssitemmodel",
            name="user_rss",
            field=models.ManyToManyField(through="rss.UserRSSItemModel", to="rss.userrssmodel"),
        ),
    ]
