# Generated by Django 4.1.3 on 2022-11-10 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RSSItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("guid", models.CharField(max_length=300)),
                ("title", models.CharField(max_length=300)),
                ("link", models.URLField(verbose_name="RSS item link")),
                ("published_date", models.DateTimeField(null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rss_item",
                "ordering": ("-published_date",),
            },
        ),
        migrations.CreateModel(
            name="RSSModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("link", models.URLField(verbose_name="RSS source link")),
                ("ttl", models.IntegerField(default=60, verbose_name="Refresh time range")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rss",
            },
        ),
        migrations.CreateModel(
            name="UserRSSModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rss",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rss.rssmodel"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "user_rss",
            },
        ),
        migrations.CreateModel(
            name="UserRSSItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rss_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rss.rssitemmodel"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "user_rss",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rss.userrssmodel"
                    ),
                ),
            ],
            options={
                "db_table": "user_rss_items",
                "ordering": ["-rss_item__published_date"],
            },
        ),
        migrations.AddField(
            model_name="rssmodel",
            name="users",
            field=models.ManyToManyField(through="rss.UserRSSModel", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="rssitemmodel",
            name="rss",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rss.rssmodel"),
        ),
        migrations.AddField(
            model_name="rssitemmodel",
            name="users",
            field=models.ManyToManyField(
                through="rss.UserRSSItemModel", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
