# Generated by Django 4.1.3 on 2022-11-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userrssitemmodel",
            name="user",
        ),
        migrations.AlterField(
            model_name="rssitemmodel",
            name="users",
            field=models.ManyToManyField(through="rss.UserRSSItemModel", to="rss.userrssmodel"),
        ),
    ]
