# Generated by Django 4.1.3 on 2022-11-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rssmodel",
            name="unavailable",
            field=models.DateTimeField(null=True),
        ),
    ]
