# Generated by Django 4.1.3 on 2022-11-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0002_auto_20221111_1230"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rssmodel",
            name="copyright",
        ),
        migrations.RemoveField(
            model_name="rssmodel",
            name="description",
        ),
        migrations.RemoveField(
            model_name="rssmodel",
            name="docs",
        ),
        migrations.RemoveField(
            model_name="rssmodel",
            name="generator",
        ),
        migrations.RemoveField(
            model_name="rssmodel",
            name="managingEditor",
        ),
        migrations.RemoveField(
            model_name="rssmodel",
            name="webMaster",
        ),
        migrations.AddField(
            model_name="rssitemmodel",
            name="author",
            field=models.CharField(default="", max_length=250, null=True),
        ),
    ]
