# Generated by Django 4.1.3 on 2022-11-11 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0003_rename_users_rssitemmodel_user_rss_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rssitemmodel",
            options={"ordering": ("-last_updated",)},
        ),
        migrations.RemoveField(
            model_name="userrssitemmodel",
            name="is_read",
        ),
    ]
