# Generated by Django 4.1.3 on 2022-11-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0004_alter_rssitemmodel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rssmodel",
            name="category",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="rssmodel",
            name="copyright",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="rssmodel",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rssmodel",
            name="docs",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="rssmodel",
            name="generator",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="rssmodel",
            name="language",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="rssmodel",
            name="managingEditor",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="rssmodel",
            name="webMaster",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
